# mysql root実行
create database loto;

# ユーザー作成(権限付与)
GRANT CREATE, SELECT, INSERT, UPDATE, DELETE ON loto.* TO u_loto@localhost IDENTIFIED BY 'aaaa';

# table 作成
create table loto.M_LOTO_TYPE( 
ID int(2), 
LOTO_TYPE_NAME VARCHAR(30), 
UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
INSERT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
ACTIVE_FLAG VARCHAR(1),
PRIMARY KEY (ID)
);

create table loto.T_EVENT_NUMBER( 
ID int(7), 
LOTO_TYPE_ID int(2),
LOTO_DATE DATE ,
EVENT_NUMBER int(7),
UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
INSERT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
ACTIVE_FLAG VARCHAR(1),
PRIMARY KEY (ID)
);

create table loto.T_LOTTERY_RESULT( 
ID int(7), 
EVENT_NUMBER_ID int(7),
LOTO_NUBERS VARCHAR(30),
BONUS_NUBERS VARCHAR(15),
UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
INSERT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
ACTIVE_FLAG VARCHAR(1),
PRIMARY KEY (ID)
);

create table loto.T_LATEST_EVENT( 
ID int(7), 
LOTO_TYPE_ID int(2),
EVENT_NUMBER_ID int(7),
UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
INSERT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
ACTIVE_FLAG VARCHAR(1),
PRIMARY KEY (ID)
);

